### ISSUE TITLE
Create Results Page UI

### ISSUE THREAD

**Issue by qaysziaey** [qaysziaey/react-quiz-app#11]

**Comment by qaysziaey** [comment]
Results Page
- Add components to the results page
- working on the UI

**Comment by Raghd7345d** [comment]
Ich mache das gerne

**Comment by Raghd7345d** [comment]
Am Mo., 5. Feb. 2024 um 12:54 Uhr schrieb qaysziaey <
***@***.***>:

**Comment by Raghd7345d** [comment]
Am Fr., 5. Apr. 2024 um 14:49 Uhr schrieb Raghad Al Abdallah <
***@***.***>:

**Comment by Raghd7345d** [comment]
Am Fr., 5. Apr. 2024 um 14:55 Uhr schrieb Raghad Al Abdallah <
***@***.***>:

**Comment by Raghd7345d** [comment]
Am Fr., 5. Apr. 2024 um 14:57 Uhr schrieb Raghad Al Abdallah <
***@***.***>:
